# Generated by Django 3.1.3 on 2020-11-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djboot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(max_length=10)),
                ('emailId', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'studentinfo',
            },
        ),
    ]
