# Generated by Django 3.1.3 on 2020-12-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impfle',
            name='img',
            field=models.ImageField(default='brand.jpg', null=True, upload_to='Profile/'),
        ),
    ]
